### PR TITLE
Removing ImageValidationIssueList reference, since the type was removed.

### PR DESCRIPTION
**Pull request by AndrewRissing**

### CODE REVIEW

**Comment by AndrewRissing** [comment]
I attempted to build the spec and noticed the above code was causing issues.

I'm not sure why we need that on the filter, so I removed it rather than putting back the ImageValidationIssueList.

@dlacroix01

**Review by dlacroix01 — COMMENTED** [review]
ImageValidationIssueList is in remote deposit. So the real question is why is the compilation failing when the type exists.  Another issue appears to be at work.

**Comment by AndrewRissing** [comment]
@dlacroix01 ImageValidationIssueList was removed out of the 5.0 branch, as part of the refactoring of the RemoteDeposit object.  I just missed this on the filter.  I don't see a reason why someone would filter by the ImageValidationIssues, so I just removed it.

**Comment by dlacroix01** [comment]
verified.  approved.

**Pull request merged**
