### PR TITLE
Added PartyId to contact to allow creating contacts for a specific user.

### PR DESCRIPTION
**Pull request by AndrewRissing**
Moved PartyId to common and updated all references to it.

### CODE REVIEW

**Comment by AndrewRissing** [comment]
@dlacroix01 Ready for review.

**Review by twardell — COMMENTED** [review]
This looks fine to me.

**Comment by AndrewRissing** [comment]
Updated to resolve merge conflicts.

**Comment by AndrewRissing** [comment]
Updated per conversation on August 28, 2019.

**Review by dlacroix01 — COMMENTED** [review]
Found just one issue in Contact.xsd  The type was corrected to PartyIdList but the element name was not modified to match.   <xs:element name="partyId" type="common:PartyIdList" .  Please revise to partyIdList and the review will be complete.  All other specifications have been reviewed by the working group. Thanks David LaCroix

**Comment by AndrewRissing** [comment]
@dlacroix01 Corrected.  Thanks for catching that.

**Review by dlacroix01 — APPROVED** [review]
Update applied as requested from working group review.

**Pull request merged**
