### PR TITLE
Adding Transaction.userMemo.

### PR DESCRIPTION
**Pull request by AndrewRissing**

### CODE REVIEW

**Comment by dlacroix01** [comment]
Discussed if there was any potential need for a memo list.  There was no evidence that would be needed. A singular element of userMemo appears to be needed. This is different from a system or organizational message that may be attached to the transaction also which is already defined in the existing object.

**Comment by dlacroix01** [comment]
More discussion needed to determine if the user making the comment needs to be captured in the sub object.

**Comment by dlacroix01** [comment]
Recommendation from working group 6/13/19
1. Add noteId  instead of userMemo to transaction,
2. Add enum of 'transaction' to coreRecordType

**Comment by AndrewRissing** [comment]
Looking at the [NotesFilter](https://github.com/cufx/standard/blob/master/CUFX/Schemas/NotesFilter.xsd), we have in relation to the CoreRecordType:
* Account - [AccountIdList](https://github.com/cufx/standard/blob/master/CUFX/Schemas/NotesFilter.xsd#L80)
* Activity - ?
* Application - [ApplicationIdList](https://github.com/cufx/standard/blob/master/CUFX/Schemas/NotesFilter.xsd#L98)
* Deposit - ?
* Loan - ?
* Portfolio - ?
* ProductServiceRequest - [ProductServiceRequestIdList](https://github.com/cufx/standard/blob/master/CUFX/Schemas/NotesFilter.xsd#L125)
* Request - ?

In addition, we have a few fields that don't seem to have a direct mapping back to the core record types:
* [AccountStatusList](https://github.com/cufx/standard/blob/master/CUFX/Schemas/NotesFilter.xsd#L89)
* [PartyIdList](https://github.com/cufx/standard/blob/master/CUFX/Schemas/NotesFilter.xsd#L107)
* [RelationshipIdList](https://github.com/cufx/standard/blob/master/CUFX/Schemas/NotesFilter.xsd#L116)

Should we add additional items to the NotesFilter to cover the above scenarios (in addition to TransactionIdList)?

**Comment by dlacroix01** [comment]
I believe the base answer is yes.  We should be supporting bi-directional navigation.  This looks like a gap. 

Thanks

David LaCroix

**Review by dlacroix01 — COMMENTED** [review]
Element addition of userMemo declined in favor of noteId.

**Comment by AndrewRissing** [comment]
@dlacroix01 Do we want to remove the following from the filter?

* AccountStatusList
* PartyIdList
* RelationshipIdList

I'm not seeing the correlation between notes and those objects.

In addition, I've got the following outstanding questions/comments:

* Referencing a deposit or loan would mean referencing an AccountId to query for it within the Notes.  It's a little awkward, but I guess works.
* I don't see an object for Portfolio or Request.  Should we remove them?

**Comment by dlacroix01** [comment]
No, those stay in.  Those are key to navigating across the standard. 

Thanks

David

**Comment by dlacroix01** [comment]
Add additional ids to detailedNote to tie out the navigation.

**Comment by AndrewRissing** [comment]
@dlacroix01 Ready for review.

**Review by dlacroix01 — APPROVED** [review]
Updates applied as discussed in the working group meeting held 8/7/19. approved.

**Pull request merged**
